const image = {
  logo: require("../image/main logo home1.png"),
  logoFooter: require("../image/Footer Logo.png"),
  imageSlider: require("../image/Frame 1.png"),
  animation1: require("../image/Animation1.png"),
  animation2: require("../image/Animation2.png"),
  animation3: require("../image/Animation3.png"),
  aboutUs: require("../image/unsplash_LRXYS0tSyGc.png"),
  user1: require("../image/unsplash_pTrhfmj2jDA.png"),
  user2: require("../image/unsplash_FVh_yqLR9eA.png"),
  user3: require("../image/unsplash_mEZ3PoFGs_k.png"),
  contact: require("../image/Contact Animations.png"),
  imgButton: require("../image/Bottom BG.png"),
  imgBackgroud1: require("../image/Footer BG 1.png"),
  imgBackgroud2: require("../image/Footer BG 2.png"),
  bubble1: require("../image/Bubble 1.png"),
  bubble2: require("../image/Bubble 2.png"),
  bubble3: require("../image/Bubble 3.png"),
  bubble4: require("../image/Bubble 4.png"),
  bubble5: require("../image/Bubble 5.png"),
  bubble6: require("../image/Bubble 6.png"),
  bgBubble1: require("../image/BG Bubble 1.png"),
  bgBubble2: require("../image/BG Bubble 2.png"),
  slider2: require("../image//slider-2.png"),
  sliderHome2: require("../image/slider-home2.png"),
  logohome2: require("../image/Main Logo home2.png"),
  play: require("../image/Polygon 1.png"),
  abouthome2: require("../image/abouhome2.png"),
  icon1: require("../image/icon-1.png"),
  icon2: require("../image/icon-2.png"),
  icon3: require("../image/icon-3.png"),
  bgSliderhome2: require("../image/Background.png"),
  groud: require("../image/Group 3.png"),
  card3: require("../image/unsplash_3ewkNkfJj2k.png"),
  card7: require("../image/unsplash_7tDGb3HrITg.png"),
  card0: require("../image/unsplash_0_McYfdyEDA.png"),
  aboutPageImg: require("../image/imageAbout.png"),
  bgAbout: require("../image/Background Mask.png"),
  bgAbout2: require("../image/Background Mask 2.png"),
  vector1: require("../image/Vector 1.png"),
  vector2: require("../image/Vector 2.png"),
  vector60: require("../image/Vector 60.png"),
  vector61: require("../image/Vector 61.png"),
  aboutll: require("../image/Illustration-2.png"),
  clientLogo: require("../image/Clients Logo.png"),
  Section: require("../image/Image Section.png"),
  animationSer: require("../image/AnimationSer1 (1).png"),
  animationSer2: require("../image/AnimationSer1 (2).png"),
  animationSer3: require("../image/AnimationSer1 (3).png"),
  sliderSer: require("../image/Background MaskSer.png"),
  sliderSer2: require("../image/unsplash_NPjNtTExSJ4.png"),
  playButton: require("../image/Play Button.png"),
  gallery: require("../image/gallery.png"),
  gallerySlider: require("../image/bgGallery1.png"),
  gallerySlider2: require("../image/bgGallery2.png"),
  playGallery: require("../image/Play ButtonGallrery.png"),
  bubbleGallery1: require("../image/Bubble 1 gallery (1).png"),
  bubbleGallery2: require("../image/Bubble 1 gallery (2).png"),
  vectorGallery1: require("../image/Vector 1Teams.png"),
  vectorGallery2: require("../image/Vector 2Teams.png"),
  teams1: require("../image/teams1.png"),
  teams2: require("../image/teams2.png"),
  teams3: require("../image/teams3.png"),
  bgTeams1: require("../image/bgTeams1.png"),
  bgTeams2: require("../image/bgTeams2.png"),
  avatar: require("../image/avatar.png"),
  sliderBlog: require("../image/SliderBlog.png"),
  cardBlog1: require("../image/cardBlog (1).png"),
  cardBlog2: require("../image/cardBlog (2).png"),
  cardBlog3: require("../image/cardBlog (3).png"),
  imgPost1: require("../image/postImage (1).png"),
  imgPost2: require("../image/postImage (2).png"),
  imgPost3: require("../image/postImage (3).png"),
  bubbleContact1: require("../image/bubbleContact (1).png"),
  bubbleContact2: require("../image/bubbleContact (2).png"),
  map: require("../image/map.png"),
  iconContactCard1: require("../image/iconCardContact (1).png"),
  iconContactCard2: require("../image/iconCardContact (2).png"),
  iconContactCard3: require("../image/iconCardContact (3).png"),
};

export default image;
